export default {
    REQUEST_STATUS: 'REQUEST_STATUS',

    LEASE_FETCH: 'LEASE_FETCH',
    LEASE_FETCH_FAILED: 'LEASE_FETCH_FAILED',

    LEASE_BY_ID_FETCH: 'LEASE_BY_ID_FETCH',
    LEASE_BY_ID_FETCH_FAILED: 'LEASE_BY_ID_FETCH_FAILED',

    LEASE_PAYMENTS_UPDATE: 'LEASE_PAYMENTS_UPDATE'
};